version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest #version confirm
    container_name: zero
    ports:
      - "5080:5080"
      - "6080:6080"
    network_mode: host
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: "100k"
        max-file: "10"
    volumes:
      - ./config.yml:/config.yml
      - ~/zero:/dgraph
    command: dgraph zero --ludicrous_mode --config /config.yml
