version: "3.2"
services:
  zero1:
    image: dgraph/dgraph:latest #should we add a specific version internally, so that the image pull process always pulls same version?
    ports:
      - "5080:5080"
      - "6080:6080"
    network_mode: host
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: "100k"
        max-file: "10"
    volumes:
      - dgraph-docker/files/config_zero.yaml:/config.yaml
      - dgraph-docker/zero:/zero
    command: dgraph zero --ludicrous_mode --config /config.yaml
