---
# tasks file for dgraph-docker
- name: make zero directory volume
  file:
    path: zero
    state: directory

- name: start dgraph by running docker-compose
  community.general.docker_compose:
    project_src: dgraph-docker/files/
