lru_mb: 2048
zero: 127.0.0.1:5080 #zero's ip
my: 127.0.0.1:7080
postings: ~/alpha/p
wal: ~/alpha/w
expose_trace: true
# whitelist: 127.0.0.1 #any ip that we want to whitelist for admin operations.
telemetry: true
max_retries: 3
mutations: allow
normalize_node_limit: 1000
query_edge_limit: 1000
idx: 1
snapshot_after: 50000
alsologtostderr: false
logtosrtderr: false
log_dir: ~/alpha/logs
