version: "3.2"
services:
  alpha:
    image: dgraph/dgraph:v20.07.2
    container_name: alpha
    ports:
      - "8080:8080"
      - "9080:9080"
    network_mode: host
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: "100k"
        max-file: "10"
    volumes:
      - ./config.yml:/config.yml
      - ~/alpha:/dgraph
    command: dgraph alpha --ludicrous_mode --config /config.yml
